
// Type definitions for d3-bullet
// Project: d3-bullet
// Definitions by: David Márquez
import { Selection, namespace } from 'd3';



export function bullet(): Bullet;

export type BulletOrientations = "right" | "left" | "top" | "bottom";

export interface Bullet {
    (sel: Selection<SVGGElement, unknown, any, unknown>): void;
    orient(): BulletOrientations;
    orient(orientation: BulletOrientations): Bullet;
    ranges(): any;
    ranges(ranges: any): Bullet;
    markers(): any;
    markers(markers: any): Bullet;
    measures(): any;
    measures(measures: any): Bullet;
    width(): number;
    width(w: number): Bullet;
    height(): number;
    height(h: number): Bullet;
    duration(): number;
    duration(ms: number): Bullet;
    /**
    * Returns the currently set tick format function, which defaults to null.
    */
    tickFormat(): ((domainValue: number, index: number) => string) | null;

    /**
     * Sets the tick format function and returns the axis.
     *
     * @param format A function mapping a value from the axis Domain to a formatted string
     * for display purposes. When invoked, the format function is also passed a second argument representing the zero-based index
     * of the tick label in the array of generated tick labels.
     */
    tickFormat(format: (domainValue: number, index: number) => string): this;

    /**
     * Reset the tick format function. A null format indicates that the scale’s
     * default formatter should be used, which is generated by calling scale.tickFormat.
     * In this case, the arguments specified by axis.tickArguments
     * are likewise passed to scale.tickFormat.
     *
     * @param format null
     */
    tickFormat(format: null): this;
}

